
project:
  type: website

website:
  title: "Curso de R con webR"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: unidad1.qmd
        text: Unidad 1
      - href: unidad2.qmd
        text: Unidad 2

format:
  html:
    theme: cosmo
    toc: true
engine: knitr
filters:
  - webr


